### ISSUE TITLE
Should have one click queue like Queue N Play does

### ISSUE THREAD

**Issue by g30h** [adeora7/youtube_queue_extension#11]
Hey I love your Extension thank you for doing it.

Would be muchj better if you had one click button overlayed onto thumbnails like Queue N Play does:
- your EXT is much better but they have overlayed buttons as shown below:

![youtube - overlayed plus buttons - queue n play chrome ext](https://user-images.githubusercontent.com/16038073/32927620-80178bc4-cb45-11e7-98c8-bbecb678db0b.PNG)

Thanks!

**Comment by adeora7** [comment]
Hey, thanks for the suggestion. I will add it soon.

**Comment by adeora7** [comment]
@g30h  One click add button added in version 1.28 !!!!
