### ISSUE TITLE
Videos with no minutes in the JSON don't add to queue

### ISSUE THREAD

**Issue by MobiusR** [adeora7/youtube_queue_extension#13]
The following snippet can be found in background.js:
```
if(   (str.split('H')).length==1 )
  var duration = (str.split('M')[0]).substring(2) + "min " + (str.split('M')[1]).split('S')[0] + "sec";
else
{
  var duration =  (str.split('H')[0]).substring(2)+ "hrs " +
                  (str.split('H')[1]).split('M')[0] + "min " +
                  (str.split('H')[1]).split('M')[1].split('S')[0] + "sec";
}
```

This algorithm of splitting up the duration can break in some scenarios.
For example take a look at https://www.youtube.com/watch?v=FV0DZhpWy2k (notice the duration is 2 hours, ZERO minutes, 35 seconds).
The duration in the googleapis JSON is "PT2H35S" (notice there is no 'M').

So you can see why the above snippet can fail in this scenario. I did not debug further than this, but I believe it may be the reason such a video is not added to the queue properly.

**Comment by adeora7** [comment]
Replacing it with this code snippet
```
str = str.substr(2);
str = str.replace("H", "hrs ");
str = str.replace("M", "mins ");
str = str.replace("S", "sec");
str = str.trim();
```

Thanks for pointing it out. :+1:

**Comment by MobiusR** [comment]
Happy to help. Great extension by the way. Very handy.
