### ISSUE TITLE
Change contributor list

### ISSUE THREAD

**Issue by adeora7** [adeora7/youtube_queue_extension#19]
Make contributor list horizontal and decrease font size of names.

**Comment by Panda2498** [comment]
I want to resolve this issue.

**Comment by adeora7** [comment]
Sure. Checkout issue #18 too. It is related to contributors' list.

**Comment by Panda2498** [comment]
Okay, I will do it

**Comment by Panda2498** [comment]
I've to make the changes in the readme.md file, right?

**Comment by adeora7** [comment]
@Panda2498  Yes

**Comment by Panda2498** [comment]
It's not happening even after removing the <br/> from between the (image + name + github account )
, it's coming in a haphazard manner after doing that.

**Comment by Panda2498** [comment]
Please update me, what should I do?

**Comment by adeora7** [comment]
Hey, sorry I was a bit busy. Will put detailed comments in the night. Sorry for the delay

**Comment by adeora7** [comment]
Hey  @Panda2498 , please take a look here https://github.com/adeora7/hacktoberfest_progress/edit/master/README.md     , you can even copy the code snippet from there. No problem if you add one or two full rows and only first 3 or 4 columns are filled. Just make sure everything is aligned properly.

**Comment by Panda2498** [comment]
Do I have to add any other names in the list of contributors?

**Comment by adeora7** [comment]
Will create another issue for that.
