### ISSUE TITLE
Badge Text doesn't update when empty queue button clicked.

### ISSUE THREAD

**Issue by adeora7** [adeora7/youtube_queue_extension#23]
Badge Text doesn't update when empty queue button clicked. Look in file `background.js`.

**Comment by Tlazypanda** [comment]
I would be interested.

**Comment by adeora7** [comment]
Please have a look in the above mentioned file. You need to find the function `empty_all` and add the piece of code to add badgetext.

**Comment by adeora7** [comment]
Also you can find that badgetext code in many functions such as play_next.
