### ISSUE TITLE
double right click doesn't work

### ISSUE THREAD

**Issue by andycjw** [adeora7/youtube_queue_extension#3]
double right clicking on playing video doesn't add the video to the queue.

can I suggest the extension to add an extra button to the youtube player to add it to the queue? you can look at how "floating for youtube" extension how to do that

https://chrome.google.com/webstore/detail/floating-for-youtube-exte/egncdnniomonjgpjbapalkckojhkfddk

**Comment by adeora7** [comment]
@andycjw  
![1](https://cloud.githubusercontent.com/assets/9638595/23965854/63c8d9f0-09df-11e7-9b9f-da1d653640dd.png)

It works. Although the suggestion is really cool and I will implement it in the next version. I am working on version 2.0 and I will definitely add it to that. Thanks :)

**Comment by andycjw** [comment]
now i get it, i thought just 'double right clicking' will add the video without clicking again on the menu like in your screenshot.

looking forward to your update on 2.0.
