### ISSUE TITLE
[request] Share queues/playlists

### ISSUE THREAD

**Issue by DARKFiB3R** [adeora7/youtube_queue_extension#4]
Just found this extension. Thank you so much, it's awesome.

Is there any way to share a queue or playlist you have created?

Doesn't look like it, but that would be a great feature too, if possible.

Thanks again :)

P.S. Sorry if this is the wrong place to ask. I don't know how to Github. :/ :)

**Comment by adeora7** [comment]
@DARKFiB3R Thanks alot. Well, version 2.0 is all about sharing only. Working on it :)

**Comment by adeora7** [comment]
Done, see the extension now
