### ISSUE TITLE
Randomize list & Reorder Queue

### ISSUE THREAD

**Issue by hackedhacker** [adeora7/youtube_queue_extension#7]
I suggest adding a feature to randomize the queue list.
Sometimes people like me, like to hear randomized song from the list I added.
And also as suggested by someone else, added someway to reorder the queue.

Just add all song in queue to an array (except current song) then randomize select 1 from the array, and play that next. So, enable/disable this feature with a button, like the loop button you made.
Do this everytime about to start a song, or just simply prepare a button to randomize the order in the queue.

**Comment by adeora7** [comment]
Adding a Queue shuffle button looks like a better option to me. Will surely add that after the current version which I am working on is deployed. Thanks :) :+1:

**Comment by pani-vishal** [comment]
I'd like to try this.

**Comment by adeora7** [comment]
Sure @falconis Please share your thoughts here before you proceed if possible.

**Comment by pani-vishal** [comment]
Sure! I will start the work tomorrow @adeora7

**Comment by americanhanko** [comment]
Ability to reorder items in the queue would be a great addition to the extension.

**Comment by pani-vishal** [comment]
I think it's best to follow what hackedhacker said. What do you say? @adeora7

**Comment by adeora7** [comment]
Yup, please go on. You can comment here for any clarification you need.
